#!/bin/bash
if [ "$1" == "build" ] ; then
    docker build -t ikom/helfertool .
elif [ "$1" == "run" ] ; then
  docker run -d \
    --name helfertool \
    -v "$PWD/test/docker/data:/data" \
    -v "$PWD/test/docker/config:/config" \
    -v "$PWD/test/docker/log:/log" \
    -p 127.0.0.1:9000:8000 ikom/helfertool
elif [ "$1" == "stop" ] ; then
    docker stop ikom/helfertool
fi
