# Generated by Django 2.2.8 on 2019-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_event_ask_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_address',
            field=models.BooleanField(default=True, verbose_name='Ask for address'),
        ),
        migrations.AddField(
            model_name='event',
            name='ask_course',
            field=models.BooleanField(default=True, verbose_name='Ask for academic course'),
        ),
        migrations.AddField(
            model_name='event',
            name='ask_fachschaft',
            field=models.BooleanField(default=True, verbose_name='Ask if Fachschaft member'),
        ),
        migrations.AddField(
            model_name='helper',
            name='member',
            field=models.BooleanField(default=False, verbose_name='Ich bin Mitglied in der Fachschaft Maschinenbau.'),
        ),
    ]
