# Generated by Django 2.2.8 on 2019-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_auto_20191208_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='city',
            field=models.CharField(default='München', max_length=60),
        ),
        migrations.AddField(
            model_name='helper',
            name='course',
            field=models.CharField(blank=True, max_length=200, verbose_name='Academic course'),
        ),
        migrations.AddField(
            model_name='helper',
            name='street',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='helper',
            name='zipcode',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
