# Generated by Django 2.2.8 on 2019-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_auto_20191208_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='city',
            field=models.CharField(default='München', max_length=60, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='member',
            field=models.BooleanField(default=False, verbose_name='I am a member of the Fachschaft Maschinenbau.'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Zipcode'),
        ),
    ]
