# Generated by Django 2.2.8 on 2020-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_auto_20191208_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ask_birthday',
            field=models.BooleanField(default=False, verbose_name='Ask for Birthday'),
        ),
        migrations.AddField(
            model_name='helper',
            name='birthday',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Academic course'),
        ),
        migrations.AddField(
            model_name='helper',
            name='street_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Street number'),
        ),
    ]
